### ISSUE TITLE
Creating Oriented Bounding Boxes on New Dataset 

### ISSUE THREAD

**Issue by Maatrika-P** [GSavathrakis/ShipRS_H2OBB#4]
Hello, you have done remarkable work!! However, in the **OBB_generation/generate.py**, only 3 datasets are supported. What do I have to do to create OBBs for my own dataset given that i have images and normal bboxes for my dataset?

**Comment by GSavathrakis** [comment]
Hello, and thank you very much for your interest in this work! 

In order to enable this method to handle your own dataset, you must first add in the argument "dataset" in the generate.py script, the name of your dataset. 

Then you should go to the OBB_generation/utils/annot_utils.py script, find the function "file_OBB_reader", and add as an option the name of your dataset in the if statements. Inside the "if" that regards your dataset, you must read the contents from your annotation file and return a numpy array with shape (n_objects, 5) where each row corresponds to an object in the file and the values are (class, center x coordinate, center y coordinate, normal box width, normal box height). 

Finally, you should go to the "create_files" function in the same script, and add an option for your dataset in the "if" statements. When you do that, write the necessary variables for the OBBs expected by your own annotation type, as well as the ground truth HBB information, using the information provided by the objs_rboxes and objs_hboxes that are given as input to the function.

I hope this information is helpful. If there is any other question feel free to ask!

**Comment by Maatrika-P** [comment]
Alright, I will make these corrections and try again. Meanwhile, I wanted to ask if this can work with low resolution data ranging from 3m resolution to 10m resolution(satellite imagery)

**Comment by GSavathrakis** [comment]
The method has not been tried yet on low resolution images but as long as the elongated axis of the object clearly occupies one of the two diagonals of the HBB, the method should work properly.
